// <auto-generated />
namespace Workflow_MVC_1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class beforepic : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(beforepic));
        
        string IMigrationMetadata.Id
        {
            get { return "201810041941268_beforepic"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
